name: MSBuild

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
  workflow_call:


permissions: write-all

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 
   
      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
   
      - name: Publish Windows EXE
        run: |
          dotnet publish . -c Release -r win-x64 -o ./publish
   
      - name: copy csv files
        continue-on-error: true    
        run: | 
          robocopy ${{ github.workspace }}\ACNHPokerCore\VillagerDatabase ${{ github.workspace }}\publish\villager
          robocopy ${{ github.workspace }}\ACNHPokerCore\csv ${{ github.workspace }}\publish\csv        
   
      - name: List publish dir 
        run: |
          dir ${{ github.workspace }}\publish\
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: Release
          path: ${{ github.workspace }}\publish\*
          overwrite: true
          retention-days: 1
   
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.upload.outputs.artifact-id }}'        
          
      - name: Output Artifact URL
        run:  echo 'Artifact URL is ${{ steps.upload.outputs.artifact-url }}'
           
      - name: list all dirs 
        run: ls -R
        
      - name: Get current time
        id: now
        uses: josStorer/get-current-time@v2
        with:
          timezone: "America/Chicago"
          format: M-D-YY-hh.mm.ss.A

      - name: Zipping up Release folder
        run: 7z a release.zip "${{ github.workspace }}\publish\"
              
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false    
          tag_name: ${{ steps.now.outputs.formattedTime }}
          body: ${{ github.event.head_commit.message }}
          files: ${{ github.workspace }}\release.zip
          name: "Release ${{ steps.now.outputs.formattedTime }}"

          
          